version: "3.6"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/productdb
      - JWT_SECRET=jsbrfjaieootjn
      - JWT_EXPIRES_IN=1h
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"